config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  root 'static_pages#home'

  scope "/:locale" do
    get 'signup', to: 'users#new'
    get 'login', to: 'user_sessions#new'
    post 'logout', to: 'user_sessions#destroy'
    root 'static_pages#home'
    resources :user_sessions, only: %i[create]
    resources :users, except: %i[new index destroy]
    post 'static_pages/check_answer'
    post 'decks/select_current_deck'
     # displays 'home' form when browser reloaded
    get 'static_pages/check_answer', to: 'static_pages#home' #code debt
    resources :cards, except: %i[show]
    resources :decks
  end

end

app/models/card.rb
# Model for keeping card data.
class Card < ApplicationRecord
  belongs_to :deck
  before_validation(on: :create) { self.review_date = Date.today }

  validates :original_text, :translated_text, :review_date, presence: true
  validates :ef, numericality: { greater_than_or_equal_to: 1.3,
                                  less_than_or_equal_to: 2.5 }
  validates :wrong_guess, numericality: { greater_than_or_equal_to: 0,
                                          less_than_or_equal_to: 3 }
  validate :not_the_same
  validate :picture_size
  scope :review_date_over, ->{ where("review_date <= ?", Date.today) }
  scope :latest, ->{ order(review_date: :asc) }
  scope :random_card, ->{ order("RANDOM()").first }
  mount_uploader :picture, PictureUploader

# assumed that distance = 1 is typo, distance greater than 1 is wrong answer
# only '<subst>' tag is typo
# book -> boko, obok - are typos, booke, ook are wrong answers
  def typo?(answer)
    return false if DamerauLevenshtein.distance(original_text, answer) > 1
    differ = DamerauLevenshtein::Differ.new
    differ.run(original_text, answer)[0].include?('<subst>')
  end

# update wrong_guess value by one
  def wrong_guess_counter
    update_attribute(:wrong_guess, wrong_guess + 1)
  end

  # check that original and translated field aren't the same
  def not_the_same
    return unless original_text.casecmp(translated_text).zero?
    errors.add(:original_text, "and translated text shouldn't be equal.")
  end

  # remove leading and trailing spaces, case insensitive,
  # compare translation with original text
  def check_translation(translation)
    original_text.casecmp(translation.strip).zero?
  end

# check that picture size less than 5MB
  def picture_size
    return unless picture.size > 5.megabytes
    errors.add(:picture, "should be less than 5MB")
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: %i[edit update destroy]

  def index
    @cards = current_cards.latest
    @number = current_cards.review_date_over.count
  end

  def new
    @card = current_cards.build
  end

  def create
    selected_deck = current_user.decks.find(params[:card][:deck_id])
    @card = selected_deck.cards.build(card_params)
    if @card.save
      flash[:success] = t('.success')
      redirect_to cards_path
    else
      flash[:danger] = t('.danger')
      render 'new'
    end
  end

  def edit; end

  def update
    if @card.update(card_params)
      flash[:success] = t('.success')
      redirect_to cards_path
    else
      flash[:danger] = t('.danger')
      render 'edit'
    end
  end

  def destroy
    @card.destroy
    flash[:success] = t('.success')
    redirect_to cards_path
  end

  private

  def card_params
    params.require(:card).permit(:original_text, :translated_text,
                                 :picture, :remote_picture_url,
                                 :deck_id)
  end

  def set_card
    @card = Card.find(params[:id])
  end
end

app/views/cards/_card.html.erb
<%= form_with model: @card, local: true do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@card.errors.count, 'error')%>
        prohibited this card from being saved:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p class="form-group">
    <%= f.label :deck_name %>
    <%= f.select :deck_id, deck_names, {}, class: "form-control" %>
    <p>Create <%= link_to 'another deck', new_deck_path %></p>
  </p>
  <p class="form-group">
    <%= f.label :original_text %>
    <%= f.text_field :original_text, class: "form-control" %>
  </p>
  <p class="form-group">
    <%= f.label :translated_text %>
    <%= f.text_field :translated_text, class: "form-control" %>
  </p>
  <% if controller.action_name == "edit" %>
  <p>current picture</p>
  <p class="form-group">
    <%= image_tag(@card.picture.url) if @card.picture.present? %>
  </p>
  <% end %>
  <p class="form-group" >
    <%= f.file_field :picture, accept: "image/jpeg,image/gif,image/png",
                               id: "card_picture", onchange: "checkSize()" %>
  </p>
  <div>OR</div><br>
  <p class="form-group" >
    <%= f.label 'Enter url to an image' %>
    <%= f.text_field :remote_picture_url, class: "form-control" %><br>
  </p>

  <p class="form-group">
    <%= f.submit class: 'bth btn-primary form-control' %>
  </p>
<% end %>

app/views/cards/_card_table.html.erb
<table class="table table-striped">
  <tr>
    <th>Picture</th>
    <th>Original</th>
    <th>Translated</th>
    <th>Review</th>
    <th>Deck Name</th>
    <th>Repetition</th>
    <th colspan="2"></th>
  </tr>
  <% @cards.each do |card| %>
    <tr>
      <td>
        <%= card.picture.present? ? image_tag(card.picture.thumb.url) : 'no'  %>
      </td>
      <td><%= card.original_text %></td>
      <td><%= card.translated_text %></td>
      <td><%= card.review_date.strftime("%d %m %Y")  if card.review_date %></td>
      <td><%= card.deck.name %></td>
      <td><%= card.repetition %></td>
      <td><%= link_to 'edit', edit_card_path(card) %></td>
      <td><%= link_to 'destroy', card_path(card), method: :delete,
                                 data: { confirm: 'Are you sure?' }%></td>
    </tr>
  <% end %>
</table>

app/views/cards/edit.html.erb
<h1>Edit card</h1>
<%= render 'card' %>
<%= link_to :back, cards_path %>

<%= @card.inspect %>

app/views/cards/index.html.erb
<h1><%= t('.all_cards')%> <%= current_deck_name %></h1>
<h2><%= t('.you_have')%> <%= t('.overdue_cards', count: @number) %></h2><br>
<%= render 'card_table' %>

app/views/cards/new.html.erb
<h1>New card</h1>
<% if current_user.decks.present? && current_deck.present? %>
  <%= render 'card' %>
<% else %>
 <p>Select current deck <%= link_to 'here', decks_path %> or
   create <%= link_to 'new deck', new_deck_path %> first</p>
<% end %>
<%= link_to :back, cards_path %>