config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  root 'static_pages#home'

  scope "/:locale" do
    get 'signup', to: 'users#new'
    get 'login', to: 'user_sessions#new'
    post 'logout', to: 'user_sessions#destroy'
    root 'static_pages#home'
    resources :user_sessions, only: %i[create]
    resources :users, except: %i[new index destroy]
    post 'static_pages/check_answer'
    post 'decks/select_current_deck'
     # displays 'home' form when browser reloaded
    get 'static_pages/check_answer', to: 'static_pages#home' #code debt
    resources :cards, except: %i[show]
    resources :decks
  end

end

app/models/deck.rb
# Model for keeping deck data.
class Deck < ApplicationRecord
  belongs_to :user
  has_many :cards, dependent: :destroy
  validates :name, presence: true
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: %i[show edit update destroy]

  def index
    @decks = current_user.decks.order(name: :asc)
  end

  def show
    @cards = @deck.cards.latest
    @number = @cards.count
  end

  def new
    @deck = current_user.decks.build
  end

  def edit; end

  def create
    @deck = current_user.decks.build(deck_params)
    if @deck.save
      flash[:success] = 'Deck was successfully created.'
      redirect_to @deck
    else
      render :new
    end
  end

  def update
    if @deck.update(deck_params)
      flash[:success] = 'Deck was successfully updated.'
      redirect_to decks_path
    else
      render :edit
    end
  end

  def destroy
    @deck.destroy
    flash[:success] = 'Deck was successfully destroyed.'
    redirect_to decks_path
  end

  def select_current_deck
    current_user.assign_current_deck(params[:current_deck_id])
    flash[:success] = 'Deck was successfully changed.'
    redirect_to decks_path
  end

  private

  def set_deck
    @deck = current_user.decks.find(params[:id])
  end

  def deck_params
    params.require(:deck).permit(:name, :id)
  end
end

app/views/decks/_form.html.erb
<%= form_with(model: deck, local: true) do |f| %>
  <% if deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(deck.errors.count, "error") %>
        prohibited this deck from being saved:
      </h2>
      <ul>
      <% deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary form-control'%>
  </div>
<% end %>

app/views/decks/_select_current_deck.html.erb
<%= form_tag(controller: :decks, action: :select_current_deck ) do %>
  <p class="form-group">
    <%= label_tag :deck_name %>
    <%= select_tag :current_deck_id,
        options_from_collection_for_select(current_user.decks, :id, :name, current_deck&.id),
        include_blank: 'all decks',
        class: 'form-control'  %>
  </p>
  <%= submit_tag 'select deck', class: 'bth btn-primary form-control' %>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<h1>Decks</h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Current</th>
      <th>Cards</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= current_deck?(deck) %></td>
        <td><%= deck.cards.count %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Deck', new_deck_path %>
<br>
<br>
<%= render 'select_current_deck' %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<table class="table table-striped">
  <tbody>
    <tr>
      <th>Name</th>
      <th>Current?</th>
    </tr>
    <tr>
      <td><%= @deck.name %></td>
      <td><%= current_deck?(@deck) %></td>
    </tr>
  </tbody>
</table>
<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>
<h3>This deck has <%= pluralize(@number, 'card')%></h3>
<br>
<%= render 'cards/card_table' %>