config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  root 'static_pages#home'

  scope "/:locale" do
    get 'signup', to: 'users#new'
    get 'login', to: 'user_sessions#new'
    post 'logout', to: 'user_sessions#destroy'
    root 'static_pages#home'
    resources :user_sessions, only: %i[create]
    resources :users, except: %i[new index destroy]
    post 'static_pages/check_answer'
    post 'decks/select_current_deck'
     # displays 'home' form when browser reloaded
    get 'static_pages/check_answer', to: 'static_pages#home' #code debt
    resources :cards, except: %i[show]
    resources :decks
  end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: :destroy

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:email], params[:password])
      flash[:success] = t('.success')
      redirect_back_or_to root_url
    else
      flash.now[:danger] = t('.danger')
      render action: :new
    end
  end

  def destroy
    logout
    flash[:success] = t('.success')
    redirect_to root_url
  end
end

app/views/user_sessions/_form.html.erb
<h3><%= t('.login_statement') %> <%= link_to t('.signup_lowcase'), signup_path %></h3>
<%= form_tag(user_sessions_path, method: :post) do %>
  <div class='form-group'>
    <%= label_tag :email %><br />
    <%= text_field_tag :email, nil, class: 'form-control' %>
  </div>
  <div class='form-group'>
    <%= label_tag :password %><br />
    <%= password_field_tag :password, nil, class: 'form-control' %>
  </div><br>
  <div class='form-group'>
    <%= submit_tag t(:login), class: 'btn btn-primary form-control' %>
  </div>
<% end %>
<p style="text-align: center;">or</p>
<p>
<%= link_to t(:login_gb), auth_at_provider_path(provider: :github),
        class: "btn btn-primary form-control", style: "background-color:#444;" %>
</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>