config/routes.rb
Rails.application.routes.draw do
  post "oauth/callback" => "oauths#callback"
  get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
  get "oauth/:provider" => "oauths#oauth", as: :auth_at_provider
  root 'static_pages#home'

  scope "/:locale" do
    get 'signup', to: 'users#new'
    get 'login', to: 'user_sessions#new'
    post 'logout', to: 'user_sessions#destroy'
    root 'static_pages#home'
    resources :user_sessions, only: %i[create]
    resources :users, except: %i[new index destroy]
    post 'static_pages/check_answer'
    post 'decks/select_current_deck'
     # displays 'home' form when browser reloaded
    get 'static_pages/check_answer', to: 'static_pages#home' #code debt
    resources :cards, except: %i[show]
    resources :decks
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Флэшкарточкер</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
         integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"
     integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"
      crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <%= link_to 'Flashcard manager', root_path, class: "navbar-brand" %>
        </div>
        <ul class="nav navbar-nav">
          <li class="<%= 'active' if controller.action_name == 'home' %>">
            <%= link_to t('.home'), root_path %>
          </li>
          <% if current_user %>
            <li><%= link_to t('.edit'), edit_user_path(current_user.id) %></li>
            <li><%= link_to t('.logout'), :logout, method: :post %></li>
            <li><%= link_to t('.decks'), decks_path %></li>
            <% if current_deck %>
              <li><%= link_to(current_deck_name, deck_path(current_deck))%></li>
            <% end %>
          <% else %>
            <li><%= link_to t('.signup'), :signup %></li>
            <li><%= link_to t(:login), :login %></li>
            <li>
              <%= link_to t(:login_gb),
                  auth_at_provider_path(provider: :github) %>
            </li>
          <% end %>
        </ul>
        <div >
          <ul class="nav navbar-nav pull-right">
            <% I18n.available_locales.each do |locale| %>
              <% if current_user %>
                <li><%= link_to locale, user_path(current_user, user: { language: locale }),
                        method: :put, style: underline(locale) %></li>
              <% else %>
                <li><%= link_to locale, { locale: locale },  style: underline(locale) %></li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>

    <section id="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <header class="clearfix" >
        <h1><%= t('.flashcardchecker') %></h1>
        <% if current_user %>
        <ul class="navigation-links">
          <li><%= link_to t('.all_cards'), cards_path %></li>
          <li>
            <%= link_to t('.add_card'), new_card_path %>
          </li>
        </ul>
        <% end %>
      </header>

      <section>
        <%= yield %>
      </section>
    </section>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>